export default {
  "*": {
    theme: { sidebar: false },
  },
  index: {
    title: "Introduction",
    theme: { sidebar: true },
  },
  "00.5-household-identification": "00.5 Household Identification",
  "01-household-members": "01 Household Members",
  "02-injured-members": "02 Injured Members",
  "03-deceased-members": "03 Deceased Members",
  "03.5-household-socio-economic-status":
    "03.5 Household Socio Economic Status",
  "04-main-source-of-income": "04 Main Source Of Income",
  "05-monthly-income": "05 Monthly Income",
  "06-external-walls-of-dwellings": "06 External Walls Of Dwellings",
  "07-roof-material": "07 Roof Material",
  "08-storeys-of-dwellings": "08 Storeys Of Dwellings",
  "09-years-built": "09 Years Built",
  "10-ownership-of-dwellings": "10 Ownership Of Dwellings",
  "11-access-to-phone": "11 Access To Phone",
  "12-access-to-radio": "12 Access To Radio",
  "12.5-individual-demographic-information":
    "12.5 Individual Demographic Information",
  "13-gender": "13 Gender",
  "14-relationship-to-head": "14 Relationship To Head",
  "15-education-levels": "15 Education Levels",
  "16-occupation-at-time": "16 Occupation At Time",
  "16.5-exposure-circumstances-during-earthquake":
    "16.5 Exposure Circumstances During Earthquake",
  "17-place-at-time": "17 Place At Time",
  "18-person-asleep": "18 Person Asleep",
  "19-attempt-to-evacuate": "19 Attempt To Evacuate",
  "20-time-to-evacuate": "20 Time To Evacuate",
  "21-struck-by-debris": "21 Struck By Debris",
  "21.5-injury-clinical-outcome": "21.5 Injury Clinical Outcome",
  "22-injured-members-yes-no": "22 Injured Members Yes No",
  "23-nature-of-injury": "23 Nature Of Injury",
  "24-severity-of-injury": "24 Severity Of Injury",
  "25-place-of-first-treatment": "25 Place Of First Treatment",
  "26-surgery": "26 Surgery",
  "27-current-status-injured": "27 Current Status Injured",
  "27.5-deceased-persons": "27.5 Deceased Persons",
  "28-deceased-by-age": "28 Deceased By Age",
  "29-deceased-by-gender": "29 Deceased By Gender",
  "30-place-of-death": "30 Place Of Death",
  "31-cause-of-death": "31 Cause Of Death",
  "32-death-certified": "32 Death Certified",
  "32.5-household-preparedness-response":
    "32.5 Household Preparedness Response",
  "33-earthquake-training": "33 Earthquake Training",
  "34-place-stayed-first-2-weeks": "34 Place Stayed First 2 Weeks",
  "35-dwellings-collapsed": "35 Dwellings Collapsed",
  "36-estimated-cost-damage": "36 Estimated Cost Damage",
  "37-loss-of-income": "37 Loss Of Income",
  "37.5-perception-suggestions": "37.5 Perception Suggestions",
  "38-assistance-received": "38 Assistance Received",
  "39-type-of-assistance": "39 Type Of Assistance",
  "40-main-reason": "40 Main Reason",
  "41-suggestions-by-interviewers": "41 Suggestions By Interviewers",
  "42-emotional-state": "42 Emotional State",
  "42.5-damage-economic-impact": "42.5 Damage Economic Impact",
  "43-proxy-of-respondents": "43 Proxy Of Respondents",
  "44-injured-members-within-walls": "44 Injured Members Within Walls",
  "44.5-interviewer-observations": "44.5 Interviewer Observations",
  "45-injured-members-within-roof": "45 Injured Members Within Roof",
  "46-injured-members-by-ownership": "46 Injured Members By Ownership",
  "46.5-association-between-injured-members-and-other-conditions":
    "46.5 Association Between Injured Members And Other Conditions",
  "47-injured-members-struck-by-debris": "47 Injured Members Struck By Debris",
  "thank-you": "Thank You",
  "00-all": "00 All Charts",
};
